application:
  name: "k8s"

database:
  dbname: "cheops"
  dbuser: "root"
  dbpassword: ""
  collections:
    - operations
    - endpoints
    - sites
    - replications
    - crosses

localsite:

knownsites:

localservices:
  - name: "api"
    address: "127.0.0.1"
