application:
  name: "k8s"

database:
  dbname: "cheops"
  dbuser: "root"
  dbpassword: ""
  collections:
    - operations
    - endpoints
    - sites
    - replications
    - crosses

knownsites:
  - local:
      name: "Paravance17"
      address: "172.16.96.17"
  - neighbor1:
      name: "Paravance18"
      address: "172.16.96.18"


localservices:
  - api:
      name: "api"
      address: "127.0.0.1"