# From https://www.tutorialspoint.com/build-and-deploy-a-flask-application-inside-docker


#Create a ubuntu base image with python 3 installed.
FROM python:3

#Set the working directory
WORKDIR /app

#copy all the files
COPY . /app

#Install the dependencies
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y sqlite3 libsqlite3-dev
RUN pip3 install -r requirements.txt

#Expose the required port
EXPOSE 5001

#Run the command
ENTRYPOINT [ "python" ]
CMD [ "app.py" ]
