apiVersion: v1
kind: PersistentVolume
metadata:
    name: data-default-hashicorp-consul-server-0
    labels:
        type: local

spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/consul/data"
